name: Vale Linter
description: The official GitHub Action for Vale -- install, manage, and run Vale with ease.
author: jdkato
branding:
  icon: check
  color: green

inputs:
  styles:
    description: A list of styles to install prior to running Vale.
    required: false

  config:
    description: An externally-hosted configuration file to use.
    required: false

  files:
    description: 'The files to lint: "all" or "<some_folder>".'
    required: false
    default: all

  onlyAnnotateModifiedLines:
    description: Only post annotations on lines that have changed within a PR.
    required: false
    default: 'false'

  reportStatusInRun:
    description: Post annotations in the workflow run and fail the step if any errors are reported.
    required: false
    default: 'false'

  debug:
    description: 'Log debugging information to stdout'
    required: false
    default: 'false'

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.styles }}
    - ${{ inputs.config }}
    - ${{ inputs.files }}
    - ${{ inputs.onlyAnnotateModifiedLines }}
    - ${{ inputs.reportStatusInRun }}
    - ${{ inputs.debug }}
